name: TEST
on:
  schedule:
    - cron: "15 2 * * *"
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
      - name: Install tesseract
        run: |
          sudo apt update
          sudo add-apt-repository universe
          sudo apt install -y tesseract-ocr
          sudo apt install -y tesseract-ocr-eng
      - name: Create .env file
        env:
          TEST_SECRET: ${{secrets.TEST_SECRET}}
        run: |
          echo "TEST_SECRET=\"$TEST_SECRET\"" >> .env
          echo "TEST_SECRET=\"$TEST_SECRET\"" >> .env
          echo "TEST_SECRET=\"$TEST_SECRET\"" >> .env
      - name: Print
        run: |
          python --version
          which tesseract
          cat .env
